# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: 'selfhosted-awsec2'

steps:

- template: build.yaml
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
    repository: $(DOCKER_REPOSITORY_NAME)
- task: ECRPushImage@1
  inputs:
    awsCredentials: 'aws_connect'
    regionName: 'eu-central-1'
    imageSource: 'imagename'
    sourceImageName: $(DOCKER_REPOSITORY_NAME)
    sourceImageTag: $(Build.BuildId)
    pushTag: latest
    repositoryName: $(DOCKER_REPOSITORY_NAME)